# Generated by Django 2.0 on 2017-12-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20171215_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='subCatOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebook.Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
