# Generated by Django 2.0 on 2017-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_auto_20171215_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
